name: Autograding - Maven JUnit

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-grade:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tdd-demo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 24
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Build and test with Maven
        run: mvn test

      - name: Count passed tests
        id: count_passed
        run: |
          PASSED=$(grep -h "Tests run:" target/surefire-reports/*.txt | awk '{split($0,a," "); print a[4]}' | paste -sd+ - | bc)
          echo "passed_tests=$PASSED" >> $GITHUB_OUTPUT

      - name: Set score
        run: 'echo "Total passed tests: ${{ steps.count_passed.outputs.passed_tests }}"'

      - name: Upload results to GitHub Classroom
        uses: education/autograding@v1
